In [ ]:
import numpy as np

In [ ]:
# 1. 1차원 numpy 배열을 만들어 결과와 같이 출력하기
#[ 0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28]

arr = np.arange(0,29,2)
arr

In [ ]:
# 2. 2차원 numpy 배열을 만들어 결과와 같이 출력하기
# [[10, 20, 30, 40],
# 50, 60, 70, 80]]

np.arange(10,81,10).reshape(2,4)

In [ ]:
# 3. 3차원 numpy 배열을 만들어 결과와 같이 출력하기
# [[[ 1, 2, 3],
# [ 4, 5, 6]],
# [[ 7, 8, 9],
# [10, 11, 12]],
# [[13, 14, 15],
# [16, 17, 18]],
# [[19, 20, 21],
# [22, 23, 24]]]

np.arange(1,25).reshape(2,4,3)

In [ ]:
# 4. 아래와 같은 행렬을 이용하여 조건에 맞는 코드 작성
# vector = np.array(range(0, 30, 2))

# 값 24 인덱싱
# 값 6 인덱싱

vector = np.array(range(0, 30, 2))
vector[-3]
vector[3]

In [ ]:
# 5. 아래와 같은 행렬을 이용하여 조건에 맞는 코드 작성
matrix = np.array([
[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12],
[13, 14, 15, 16]
])

# 1)- 값 8 인덱싱
matrix[1,-1]

# 2)- 값 2 인덱싱
matrix[0,1]

# 3)- 값 9 인덱싱
matrix[2,0]

# 4)- 값 15 인덱싱
matrix[-1,-2]

In [ ]:
# 6. 아래와 같은 행렬을 작성해보세요
# [-1, -2, -3, -4, -5]

np.arange(-1,-6,-1)

In [ ]:
# 7.다음 행렬과 같은 배열이 있다.

x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
              11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

# 1)이 배열에서 3의 배수를 찾아라.
print(x[x % 3 == 0])

# 2)이 배열에서 4로 나누면 1이 남는 수를 찾아라.
print(x[x % 4 == 1])

# 3)이 배열에서 3으로 나누면 나누어지고 4로 나누면 1이 남는 수를 찾아라.
print(x[(x % 3 == 0) & (x % 4 == 1)])

In [ ]:
# 8. 다음 배열을 만들고 슬라이싱, 인덱싱 연습하세요
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d

# 1) 특정 원소에 접근
print(arr2d[1,1]) # arr2d[행 인덱스, 열 인덱스]
# 5

# 2) 특정 행에 접근
print(arr2d[0]) # arr2d[행 인덱스]
# [1 2 3]

# 3) 특정 열에 접근
print(arr2d[:,2]) # arr2d[:, 열 인덱스]
# [3 6 9]

#4) 부분 배열(슬라이스) 생성
print(arr2d[:2, 1:]) # arr2d[시작 행:끝 행, 시작 열:끝 열]
#[[2 3]
#[5 6]]

# 5) 특정 행 범위에 접근
print(arr2d[0:2]) # arr2d[시작 행:끝 행]
# [[1 2 3]
# [4 5 6]]

# 6 특정 열 범위에 접근
print(arr2d[:,0:2])  # arr2d[:, 시작 열:끝 열]
# [[1 2]
#  [4 5]
#  [7 8]]

# 7) 마지막 열에 접근
print(arr2d[:,-1]) # arr2d[:, 음수 인덱스]
#[3 6 9]

# 8) 부분 배열에 새로운 값을 할당
arr2d[:2, 1:] =0 # arr2d[시작 행:끝 행, 시작 열:끝 열]
print(arr2d)
# [[1 0 0]
#  [4 0 0]
#  [7 8 9]]